modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/InventoryEssentials/issues"

[[mods]]
modId="inventoryessentials"
version="${file.jarVersion}"
displayName="Inventory Essentials"
displayURL="https://blay09.net/mods/inventoryessentials"
logoFile="inventoryessentials-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Basic inventory tweaks. Lightweight and compatible.
'''

[[dependencies.inventoryessentials]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryessentials]]
    modId="balm"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
