modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/InventoryEssentials/issues"

[[mods]]
modId="inventoryessentials"
version="${mod_version}"
displayName="Inventory Essentials"
displayURL="https://mods.twelveiterations.com/mc/inventoryessentials"
logoFile="inventoryessentials-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Basic inventory tweaks. Lightweight and compatible.
'''

[[dependencies.inventoryessentials]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventoryessentials]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
