modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/blay09/InventoryEssentials/issues"
displayURL="https://minecraft.curseforge.com/projects/inventory-essentials"
authors="BlayTheNinth"

[[mods]]
modId="inventoryessentials"
version="${file.jarVersion}"
displayName="Inventory Essentials"
description='''
Basic inventory control enhancements. The best of all, and nothing else.
'''
